### ISSUE TITLE
关于check_parentheses

### ISSUE THREAD

**Issue by moukyh** [CR400AF2001/NJU-ICS-PA2020_fall#1]

**Comment by moukyh** [comment]
最后没有判断left==right，是否可能出现"(()"的情况使得测试有误？

**Comment by CR400AF2001** [comment]
我看了一下应该是不会的，这次check_parentheses返回true以后，会在原eval函数里继续递归调用eval，此时进行判断的串是"("，这时候check_parentheses还是会返回false。
